server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://193.112.86.154:3306/zxf?serverTimezone=UTC
    username: root
    password: .666.

    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 193.112.86.154
    port: 6379
    timeout: 3000
    password: .777.
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8

  jpa:
    show-sql: true

  rabbitmq:
    host: 193.112.86.154
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 30000


  management:
    endpoint:
      health:
        enabled:true

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token
